mqtt:
  enabled: true
  host: 10.30.0.254
  port: 1883
  user: "frigate"
  password: "@lb3rt0-Frigate"

ffmpeg:
  input_args: preset-rtsp-generic

objects:
  track:
    - person
    - car
    - dog

# Global recording settings
record:
  enabled: true
  retain:
    days: 30        # Keep all recordings for 30 days
    mode: motion   # Only record when motion detected

cameras:
  front_garden:
    enabled: true
    ffmpeg:
      inputs:
        # Main stream for recording (high quality)
        - path: rtsp://admin:@lb3rt0-Homelab@10.40.0.12:554/Streaming/Channels/101
          roles:
            - record
        # Sub stream for detection (low quality = less CPU)
        - path: rtsp://admin:@lb3rt0-Homelab@10.40.0.12:554/Streaming/Channels/202
          roles:
            - detect
    detect:
      enabled: true
      width: 896
      height: 512
      fps: 5
    record:
      enabled: true
      alerts:
        retain:
          days: 14  # Keep important detections longer
        pre_capture: 5
        post_capture: 5
      detections:
        retain:
          days: 7
        pre_capture: 3
        post_capture: 3
#  backyard:
#    enabled: false
#    ffmpeg:
#      inputs:
        # Main stream for recording (high quality)
#        - path: rtsp://admin:@lb3rt0-Homelab@10.40.0.11:554/Streaming/Channels/101
#          roles:
#            - record
        # Sub stream for detection (low quality = less CPU)
#        - path: rtsp://admin:@lb3rt0-Homelab@10.40.0.11:554/Streaming/Channels/202
#          roles:
#            - detect
#    detect:
#      enabled: true
#      width: 896
#      height: 512
#      fps: 5
#    record:
#      enabled: true
#      alerts:
#        retain:
#          days: 14  # Keep important detections longer
#        pre_capture: 5
#        post_capture: 5
#      detections:
#        retain:
#          days: 7
#        pre_capture: 3
#        post_capture: 3