#version: '3.8'

services:
  # AlbertoVE NVR
#  albertove:
#    container_name: albertove
#    build: .
#    restart: unless-stopped
#    ports:
#      - "8080:8080"  # NVR web + API
#    volumes:
#      - /mnt/recordings:/recordings
#      - ./config.yaml:/app/config.yaml
#    environment:
#      STORAGE_ROOT: /recordings
#      WEB_ADDR: 0.0.0.0:8080
#    depends_on:
#      - mqtt
#    networks:
#      - home_automation

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    ports:
      - "8123:8123"
    volumes:
      - ha_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      TZ: "Europe/Amsterdam"

volumes:
  ha_config:

