#version: '3.8'

services:

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ha_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      TZ: "Europe/Amsterdam"

  chrony:
    image: cturra/ntp:latest
    container_name: chrony
    restart: unless-stopped
    ports:
      - "123:123/udp"
    environment:
      - NTP_SERVERS=0.nl.pool.ntp.org,1.nl.pool.ntp.org,2.nl.pool.ntp.org,3.nl.pool.ntp.org
    cap_add:
      - SYS_TIME
    read_only: true

  nut:
    image: instantlinux/nut-upsd:latest
    container_name: nut
    restart: unless-stopped
    ports:
      - "3493:3493"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./configs/nut:/etc/nut
    environment:
      - ADMIN_USER=${NUT_ADMIN_USER}
      - ADMIN_PASSWORD=${NUT_ADMIN_PASSWORD}
      - DRIVER=usbhid-ups
      - PORT=auto
      - UPS_NAME=ups
    privileged: true

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"  # Increase to 128mb+ for more cameras
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000  # 1GB RAM cache
    ports:
      - "5000:5000"      # Web UI
      - "8554:8554"      # RTSP feeds
      - "8555:8555/tcp"  # WebRTC
      - "8555:8555/udp"  # WebRTC
    environment:
      - FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PASSWORD}

volumes:
  ha_config:

