cameras:
  - id: cam1
    rtsp_url: rtsp://10.10.0.134:554/live
    segment_time: 10
    output_dir: /mnt/recordings/cam1
  - id: cam2
    rtsp_url: rtsp://10.10.0.134:554/live
    segment_time: 10
    output_dir: /mnt/recordings/cam2

# rtsp_url: rtsp://admin:@lberto-homelab@10.40.0.11/Streaming/channels/101
# rtsp_url: rtsp://admin:@lberto-homelab@10.40.0.12/Streaming/channels/101